spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
        id.optimizer.pooled.preferred: pooled-lo

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  jackson:
    serialization:
      indent_output: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: https://duckstar.kr/login/oauth2/code/kakao
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080
  forward-headers-strategy: native        # Nginx 뒤에서 X-Forwarded-* 신뢰
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/javascript,text/css,text/html,text/xml,text/plain

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN

app:
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
  cookie:
    same-site: None
    secure: true
  base-url: https://duckstar.kr

jwt:
  secret: ${JWT_SECRET}
  issuer: "duckstar.kr"

cloud:
  aws:
    s3:
      bucket: img.duckstar.kr